### ISSUE TITLE
Unable to run multiple instance of markserv

### ISSUE THREAD

**Issue by wzhliang** [markserv/markserv#104]
Platform: MacOs

To reproduce:

1. run 1st instance: `markserv .`
2. run 2nd instance: `mark serve -p 7777 .`

got the following error:

    events.js:187
          throw er; // Unhandled 'error' event
          ^

    Error: listen EADDRINUSE: address already in use :::35729`

**Comment by tofuZiggy** [comment]
Sorry a little late... but ...
You have to also change the listening port in order to run a second instance of markserv. By default it will try to listen on 35729 so that will throw an error when you go to start the second instance.

`markserv -p 7777 --livereloadport 7778`

In theory you can use the `-l` option but I could never get that working and had to spell out `--livereloadport`
